[package]
name = "ddf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Discrete differential-form operators for the formoniq thesis fork"

[dependencies]
exterior = { path = "../exterior" }
manifold = { path = "../manifold" }
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"
