name: Rust CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo check --release --workspace --all-targets
      - run: cargo test --release --workspace
      - run: cargo clippy --release --workspace --all-targets -- -D warnings
      - run: cargo doc --release --workspace --no-deps
